// Generated by gencpp from file first_package/TwoInts.msg
// DO NOT EDIT!


#ifndef FIRST_PACKAGE_MESSAGE_TWOINTS_H
#define FIRST_PACKAGE_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <first_package/TwoIntsRequest.h>
#include <first_package/TwoIntsResponse.h>


namespace first_package
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace first_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_package::TwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::first_package::TwoInts&) { return value(); }
};

template<>
struct DataType< ::first_package::TwoInts > {
  static const char* value()
  {
    return "first_package/TwoInts";
  }

  static const char* value(const ::first_package::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::first_package::TwoIntsRequest> should match 
// service_traits::MD5Sum< ::first_package::TwoInts > 
template<>
struct MD5Sum< ::first_package::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::TwoInts >::value();
  }
  static const char* value(const ::first_package::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::TwoIntsRequest> should match 
// service_traits::DataType< ::first_package::TwoInts > 
template<>
struct DataType< ::first_package::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::first_package::TwoInts >::value();
  }
  static const char* value(const ::first_package::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_package::TwoIntsResponse> should match 
// service_traits::MD5Sum< ::first_package::TwoInts > 
template<>
struct MD5Sum< ::first_package::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::TwoInts >::value();
  }
  static const char* value(const ::first_package::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::TwoIntsResponse> should match 
// service_traits::DataType< ::first_package::TwoInts > 
template<>
struct DataType< ::first_package::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::first_package::TwoInts >::value();
  }
  static const char* value(const ::first_package::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PACKAGE_MESSAGE_TWOINTS_H
